#!/bin/bash
#SBATCH --account=torma
#SBATCH --ntasks=10
#SBATCH --mem=20gb
#SBATCH --time=5:00:00
#SBATCH --partition=small
#SBATCH --job-name="NONAME"

export NPROCS=$SLURM_NTASKS
NPOOLS=`python3 -c "print($NPROCS / 4)"`
export NPOOLS
