# dftCaddie user configuration
# ============================
# Users can extend this file to add new calculation kinds, clusters,
# MPI executables, or pseudopotential mappings.

# Folder in which pseudopotentials are stored. Overwritten by env variable $PSLIBRARY (if present).
pseudopotentials:
  root: /opt/pslibrary

# Supported calculations and required files (located at dftcaddie/data)
calculations:
  bands:
    name: "[B]ands"
    config:
      - name: code
        prompt: "Available codes:"
        options:
          - quantum_espresso
          - vasp
      - name: soc
        type: bool
        prompt: "Spin–orbit coupling:"
        options:
          - true
          - false
        default: true
    files:
      quantum_espresso:
        - scf.sh
        - bands.sh
        - project_bands.sh
      vasp:
        - INCAR.SCC
        - INCAR.BS
        - KPOINTS.SCC
        - scf.sh
        - bands.sh
  relax:
    name: "[R]elax"
    config:
      - name: code
        prompt: "Available codes:"
        options:
          - quantum_espresso
          - vasp
      - name: soc
        type: bool
        prompt: "Spin–orbit coupling:"
        options:
          - true
          - false
        default: false
      - name: cell_relaxation
        type: bool
        prompt: "Cell relaxation?"
        options:
          - true
          - false
    files:
      quantum_espresso:
        - relax.sh
      vasp:
        - INCAR.RELAX
        - KPOINTS.SCC
        - relax.sh
  phonons:
    name: "[P]honons"
    config:
      - name: code
        prompt: "Available codes:"
        options:
          - quantum_espresso
      - name: soc
        type: bool
        prompt: "Spin–orbit coupling:"
        options:
          - true
          - false
        default: false
    files:
      quantum_espresso:
        - scf.sh
        - ph.sh
        - matdyn.sh

# Supported clusters with custom preambles located at dftcaddie/data
clusters:
  local:
    hostname: ""
    mpi_command: "mpiexec -np 2"
    headers:
      - name: default
        file: default
  ekhi:
    hostname: "ekhi"
    mpi_command: "mpiexec -np $NPROCS"
    headers:
      - name: default
        file: ekhi
  triton:
    hostname: "triton"
    mpi_command: "srun"
    headers:
      - name: default
        file: triton
  puhti:
    hostname: "puhti"
    mpi_command: "srun"
    headers:
      - name: default
        file: puhti_mahti
  mahti:
    hostname: "mahti"
    mpi_command: "srun"
    headers:
      - name: default
        file: puhti_mahti
  planck:
    hostname: "login"
    mpi_command: "srun --mpi=pmi2"
    headers:
      - name: default
        file: planck
      - name: intelnodes
        file: planck
      - name: intelnewnodes
        file: planck
      - name: amdnodes
        file: planck

# Mpi executables over which to attach the cluster specific mpi_commands
mpi_executables:
  - pw.x
  - projwfc.x
  - ph.x
  - vasp_ncl

# Suggested pseudopotentials (same as suggested in pslibrary repository)
suggested_qe_pseudos:
  H: "H.$fct-*_psl.1.0.0"
  He: "He.$fct-*_psl.1.0.0"
  Li: "Li.$fct-sl-*_psl.1.0.0"
  Be: "Be.$fct-sl-*_psl.1.0.0"
  B: "B.$fct-n-*_psl.1.0.0"
  C: "C.$fct-n-*_psl.1.0.0"
  N: "N.$fct-n-*_psl.1.0.0"
  O: "O.$fct-n-*_psl.1.0.0"
  F: "F.$fct-n-*_psl.1.0.0"
  Ne: "Ne.$fct-n-*_psl.1.0.0"
  Na: "Na.$fct-spnl-*_psl.1.0.0"
  Mg: "Mg.$fct-spnl-*_psl.1.0.0"
  Al: "Al.$fct-nl-*_psl.1.0.0"
  Si: "Si.$fct-nl-*_psl.1.0.0"
  P: "P.$fct-nl-*_psl.1.0.0"
  S: "S.$fct-nl-*_psl.1.0.0"
  Cl: "Cl.$fct-nl-*_psl.1.0.0"
  Ar: "Ar.$fct-nl-*_psl.1.0.0"
  K: "K.$fct-spn-*_psl.1.0.0"
  Ca: "Ca.$fct-spn-*_psl.1.0.0"
  Sc: "Sc.$fct-spn-*_psl.1.0.0"
  Ti: "Ti.$fct-spn-*_psl.1.0.0"
  V: "V.$fct-spnl-*_psl.1.0.0"
  Cr: "Cr.$fct-spn-*_psl.1.0.0"
  Mn: "Mn.$fct-spn-*_psl.0.3.1"
  Fe: "Fe.$fct-n-*_psl.1.0.0"
  Co: "Co.$fct-n-*_psl.0.3.1"
  Ni: "Ni.$fct-n-*_psl.1.0.0"
  Cu: "Cu.$fct-dn-*_psl.1.0.0"
  Zn: "Zn.$fct-dn-*_psl.1.0.0"
  Ga: "Ga.$fct-dnl-*_psl.1.0.0"
  Ge: "Ge.$fct-n-*_psl.1.0.0"
  As: "As.$fct-n-*_psl.1.0.0"
  Se: "Se.$fct-n-*_psl.1.0.0"
  Br: "Br.$fct-n-*_psl.1.0.0"
  Kr: "Kr.$fct-dn-*_psl.1.0.0"
  Rb: "Rb.$fct-spn-*_psl.1.0.0"
  Sr: "Sr.$fct-spn-*_psl.1.0.0"
  Y: "Y.$fct-spn-*_psl.1.0.0"
  Zr: "Zr.$fct-spn-*_psl.1.0.0"
  Nb: "Nb.$fct-spn-*_psl.1.0.0"
  Mo: "Mo.$fct-spn-*_psl.1.0.0"
  Tc: "Tc.$fct-spn-*_psl.0.3.0"
  Ru: "Ru.$fct-spn-*_psl.1.0.0"
  Rh: "Rh.$fct-spn-*_psl.1.0.0"
  Pd: "Pd.$fct-n-*_psl.1.0.0"
  Ag: "Ag.$fct-n-*_psl.1.0.0"
  Cd: "Cd.$fct-n-*_psl.1.0.0"
  In: "In.$fct-dn-*_psl.1.0.0"
  Sn: "Sn.$fct-dn-*_psl.1.0.0"
  Sb: "Sb.$fct-n-*_psl.1.0.0"
  Te: "Te.$fct-n-*_psl.1.0.0"
  I: "I.$fct-n-*_psl.1.0.0"
  Xe: "Xe.$fct-dn-*_psl.1.0.0"
  Cs: "Cs.$fct-spnl-*_psl.1.0.0"
  Ba: "Ba.$fct-spn-*_psl.1.0.0"
  La: "La.$fct-spfn-*_psl.1.0.0"
  Ce: "Ce.$fct-spdn-*_psl.1.0.0"
  Pr: "Pr.$fct-spdn-*_psl.1.0.0"
  Nd: "Nd.$fct-spdn-*_psl.1.0.0"
  Pm: "Pm.$fct-spdn-*_psl.1.0.0"
  Sm: "Sm.$fct-spdn-*_psl.1.0.0"
  Eu: "Eu.$fct-spn-*_psl.1.0.0"
  Gd: "Gd.$fct-spdn-*_psl.1.0.0"
  Tb: "Tb.$fct-spdn-*_psl.1.0.0"
  Dy: "Dy.$fct-spdn-*_psl.1.0.0"
  Ho: "Ho.$fct-spdn-*_psl.1.0.0"
  Er: "Er.$fct-spdn-*_psl.1.0.0"
  Tm: "Tm.$fct-spdn-*_psl.1.0.0"
  Yb: "Yb.$fct-spn-*_psl.1.0.0"
  Lu: "Lu.$fct-spdn-*_psl.1.0.0"
  Hf: "Hf.$fct-spn-*_psl.1.0.0"
  Ta: "Ta.$fct-spn-*_psl.1.0.0"
  W: "W.$fct-spn-*_psl.1.0.1"
  Re: "Re.$fct-spn-*_psl.1.0.0"
  Os: "Os.$fct-spn-*_psl.1.0.0"
  Ir: "Ir.$fct-n-*_psl.0.2.3"
  Pt: "Pt.$fct-n-*_psl.1.0.0"
  Au: "Au.$fct-n-*_psl.1.0.1"
  Hg: "Hg.$fct-n-*_psl.1.0.0"
  Tl: "Tl.$fct-dn-*_psl.1.0.0"
  Pb: "Pb.$fct-dn-*_psl.1.0.0"
  Bi: "Bi.$fct-dn-*_psl.1.0.0"
  Po: "Po.$fct-dn-*_psl.1.0.0"
  At: "At.$fct-dn-*_psl.1.0.0"
  Rn: "Rn.$fct-dn-*_psl.1.0.0"
  Fr: "Fr.$fct-spdn-*_psl.1.0.0"
  Ra: "Ra.$fct-spdn-*_psl.1.0.0"
  Ac: "Ac.$fct-spfn-*_psl.1.0.0"
  Th: "Th.$fct-spfn-*_psl.1.0.0"
  Pa: "Pa.$fct-spfn-*_psl.1.0.0"
  U: "U.$fct-spfn-*_psl.1.0.0"
  Np: "Np.$fct-spfn-*_psl.1.0.0"
  Pu: "Pu.$fct-spfn-*_psl.1.0.0"
